# Generated by Django 4.0.5 on 2022-07-01 11:17

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_post_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post',
            field=tinymce.models.HTMLField(),
        ),
    ]
