# Generated by Django 4.0.6 on 2022-08-21 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('posts', '0007_alter_comment_options_alter_post_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='topic',
            field=models.ManyToManyField(blank=True, related_name='topics', to='categories.topic'),
        ),
    ]
