# Generated by Django 4.0.5 on 2022-07-01 13:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_userprofile_age_userprofile_github_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='subscribers',
            fields=[
                ('name', models.CharField(max_length=200, null=True)),
                ('email', models.EmailField(max_length=250)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
