version: '3.8'


services:
  website:
    container_name: website
    build: .
    ports: 
      - 8000:8000
    volumes:
      - .:/app
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - psql
  psql:
    image: postgres
    container_name: psql
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=aslon2001
    volumes:
      - pdata:/var/lib/postgresql/data

volumes:
  pdata:

    
      



